
exports.SHEETS = [
  'Team',
  'Card types',
  'Cards',
  'Murmurs',
];

exports.RELATED_CARD_FIELDS = [
  'Feature',
  'Story',
  'Related Story'
];

exports.FIELDS_WITH_LABELS = [
  'Tags',
  'Status',
  'Severity',
  'Type'
];


exports.DATE_OPERATORS = {
  MIN: 1,
  MAX: 2,
};

exports.MOBILE_DATE_FIELDS = [
    'Date Accepted(Hidden)',
    'Date Analysis Ended(Hidden)',
    'Date Analysis Started(Hidden)',
    'Date Created(Hidden)',
    'Date Development Ended(Hidden)',
    'Date Development Started(Hidden)',
    'Date Fixed(Hidden)',
    'Date Reported(Hidden)',
    'Date Testing Ended(Hidden)',
    'Date Testing Started(Hidden)',
    'Moved to Accepted on(Hidden)',
    'Moved to Backlog on(Hidden)',
    'Moved to Business Analysis on(Hidden)',
    'Moved to Cannot Reproduce on(Hidden)',
    'Moved to Deleted on(Hidden)',
    'Moved to Development Complete on(Hidden)',
    'Moved to Duplicate on(Hidden)',
    'Moved to In Analysis on(Hidden)',
    'Moved to In Development on(Hidden)',
    'Moved to In Testing on(Hidden)',
    'Moved to Not a Bug on(Hidden)',
    'Moved to Ready for Analysis on(Hidden)',
    'Moved to Ready for Development on(Hidden)',
    'Moved to Ready for Signoff on(Hidden)',
    'Moved to Ready for Testing on(Hidden)'
  ];

exports.BO_DATE_FIELDS = [
  'Moved to Accepted on(Hidden)',
  'Moved to Accepted on 1(Hidden)',
  'Moved to Archive on(Hidden)',
  'Moved to Archive on 1(Hidden)',
  'Moved to Archive on 2(Hidden)',
  // 'Moved to Backlog on(Hidden)',
  // 'Moved to Backlog on 1(Hidden)',
  // 'Moved to Backlog on 2(Hidden)',
  'Moved to Business Analysis on(Hidden)',
  'Moved to Business Analysis on 1(Hidden)',
  'Moved to Cannot Reproduce on(Hidden)',
  'Moved to Cannot Reproduce on 1(Hidden)',
  // 'Moved to Deleted on(Hidden)',
  // 'Moved to Deleted on 1(Hidden)',
  // 'Moved to Development Complete on(Hidden)',
  // 'Moved to Development Complete on 1(Hidden)',
  // 'Moved to Doing on(Hidden)',
  // 'Moved to Done on(Hidden)',
  // 'Moved to Duplicate on(Hidden)',
  // 'Moved to Duplicate on 1(Hidden)',
  'Moved to In Analysis on(Hidden)',
  'Moved to In Analysis on 1(Hidden)',
];

exports.DATE_FIELDS = [
  'Date Accepted(Hidden)',
  'Date Analysis Ended(Hidden)',
  'Date Analysis Started(Hidden)',
  'Date Created(Hidden)',
  'Date Development Ended(Hidden)',
  'Date Development Started(Hidden)',
  'Date Fixed(Hidden)',
  'Date Reported(Hidden)',
  'Date Testing Ended(Hidden)',
  'Date Testing Started(Hidden)',
  'Moved to Accepted on(Hidden)',
  'Moved to Backlog on(Hidden)',
  'Moved to Business Analysis on(Hidden)',
  'Moved to Cannot Reproduce on(Hidden)',
  'Moved to Deleted on(Hidden)',
  'Moved to Development Complete on(Hidden)',
  'Moved to Duplicate on(Hidden)',
  'Moved to In Analysis on(Hidden)',
  'Moved to In Development on(Hidden)',
  'Moved to In Testing on(Hidden)',
  'Moved to Not a Bug on(Hidden)',
  'Moved to Ready for Analysis on(Hidden)',
  'Moved to Ready for Development on(Hidden)',
  'Moved to Ready for Signoff on(Hidden)',
  'Moved to Ready for Testing on(Hidden)',
  'Moved to Accepted on 1(Hidden)',
  'Moved to Archive on(Hidden)',
  'Moved to Archive on 1(Hidden)',
  'Moved to Archive on 2(Hidden)',
  'Moved to Backlog on 1(Hidden)',
  'Moved to Backlog on 2(Hidden)',
  'Moved to Business Analysis on 1(Hidden)',
  'Moved to Cannot Reproduce on 1(Hidden)',
  'Moved to Deleted on 1(Hidden)',
  'Moved to Development Complete on 1(Hidden)',
  'Moved to Doing on(Hidden)',
  'Moved to Done on(Hidden)',
  'Moved to Duplicate on 1(Hidden)',
  'Moved to In Analysis on 1(Hidden)',
  'Moved to In Development on 1(Hidden)',
  'Moved to In Testing on 1(Hidden)',
  'Moved to Not a Bug on 1(Hidden)',
  'Moved to Ready for Analysis on 1(Hidden)',
  'Moved to Ready for Development on 1(Hidden)',
  'Moved to Ready for Signoff on 1(Hidden)',
  'Moved to Ready for Testing on 1(Hidden)',
  'Moved to To do on(Hidden)',
];

exports.COLUMNS_CARDS = [
  'Number',
  'Name',
  'Description (Plain text)',
  'Description (HTML)',
  'Type',
  // 'Age of Defect',
  // 'Completed Points',
  // 'Completed Points - Feature',
  // 'Date Accepted(Hidden)',
  // 'Date Analysis Ended(Hidden)',
  // 'Date Analysis Started(Hidden)',
  // 'Date Created(Hidden)',
  // 'Date Development Ended(Hidden)',
  // 'Date Development Started(Hidden)',
  // 'Date Fixed(Hidden)',
  // 'Date Reported(Hidden)',
  // 'Date Testing Ended(Hidden)',
  // 'Date Testing Started(Hidden)',
  // 'Days Open(Hidden)',
  // 'Delta Points',
  // 'Delta Velocity',
  'Developer',
  // 'End Date',
  'Exclude from Release Notes',
  'Feature', // (e.g. "#6157 Add new routes for form and report views")
  'FreshDesk', // (e.g. 4207)
  // 'Integration Processed(Hidden)',
  'Iteration', // (e.g. "#5491 Iteration 136")
  // 'Iteration Accepted(Hidden)',
  // 'Iteration Created(Hidden)',
  // 'Iteration Defect Fixed(Hidden)',
  // 'Iteration Development Completed(Hidden)',
  // 'Iteration Testing Completed(Hidden)',
  'Module',
  // 'Moved to Accepted on(Hidden)',
  // 'Moved to Backlog on(Hidden)',
  // 'Moved to Business Analysis on(Hidden)',
  // 'Moved to Cannot Reproduce on(Hidden)',
  // 'Moved to Deleted on(Hidden)',
  // 'Moved to Development Complete on(Hidden)',
  // 'Moved to Duplicate on(Hidden)',
  // 'Moved to In Analysis on(Hidden)',
  // 'Moved to In Development on(Hidden)',
  // 'Moved to In Testing on(Hidden)',
  // 'Moved to Not a Bug on(Hidden)',
  // 'Moved to Ready for Analysis on(Hidden)',
  // 'Moved to Ready for Development on(Hidden)',
  // 'Moved to Ready for Signoff on(Hidden)',
  // 'Moved to Ready for Testing on(Hidden)',
  'Order',
  'Owner',
  // 'Percent Complete',
  // 'Percent Complete - Feature',
  'Persona',
  // 'Points Completed',
  // 'Points Scheduled',
  // 'Product Roadmap - Release',
  // 'Promised Iteration',
  'Pull Request', // (e.g. 5369)
  // 'Pull Request Link(Hidden)',
  'QA',
  'Related Story', // (e.g. "#5369 Add PDF Font support for special characters")
  'Release', // (e.g. "#5696 2018 Q2")
  // 'Release Defect Fixed(Hidden)',
  // 'Release Defect Identified(Hidden)',
  'Severity',
  // 'Simple Status(Hidden)',
  // 'Start Date',
  'Status',
  'Story', // (e.g. "#5369 Add PDF Font support for special characters")
  'Story Points',
  // 'System(Hidden)',
  // 'Target Release',
  // 'Target Velocity',
  'Task Status',
  // 'Theme',
  // 'Total Points',
  // 'Total Points - Feature',
  // 'Total Points in Iteration',
  // 'Velocity',
  // 'Version',
  'Created by',
  'Modified by',
  'Tags',
  // 'Incomplete checklist items',
  // 'Complete checklist items',
  'Attachments',
  // 'Has charts',
  // 'Charts and macros',
];

const backofficeFields = [
  'Number',
  'Name',
  'Description (Plain text)',
  'Description (HTML)',
  'Type',
  'Back Office Roadmap - Release',
  'Exclude from Release Notes',
  'Feature',
  'FreshDesk',
  'Iteration',
  'Managed Package',
  'Moved to Accepted on(Hidden)',
  'Moved to Accepted on 1(Hidden)',
  'Moved to Archive on(Hidden)',
  'Moved to Archive on 1(Hidden)',
  'Moved to Archive on 2(Hidden)',
  // 'Moved to Backlog on(Hidden)',
  // 'Moved to Backlog on 1(Hidden)',
  // 'Moved to Backlog on 2(Hidden)',
  'Moved to Business Analysis on(Hidden)',
  'Moved to Business Analysis on 1(Hidden)',
  'Moved to Cannot Reproduce on(Hidden)',
  'Moved to Cannot Reproduce on 1(Hidden)',
  // 'Moved to Deleted on(Hidden)',
  // 'Moved to Deleted on 1(Hidden)',
  // 'Moved to Development Complete on(Hidden)',
  // 'Moved to Development Complete on 1(Hidden)',
  // 'Moved to Doing on(Hidden)',
  // 'Moved to Done on(Hidden)',
  // 'Moved to Duplicate on(Hidden)',
  // 'Moved to Duplicate on 1(Hidden)',
  'Moved to In Analysis on(Hidden)',
  'Moved to In Analysis on 1(Hidden)',
  // 'Moved to In Development on(Hidden)',
  // 'Moved to In Development on 1(Hidden)',
  // 'Moved to In Testing on(Hidden)',
  // 'Moved to In Testing on 1(Hidden)',
  // 'Moved to Not a Bug on(Hidden)',
  // 'Moved to Not a Bug on 1(Hidden)',
  // 'Moved to Ready for Analysis on(Hidden)',
  // 'Moved to Ready for Analysis on 1(Hidden)',
  // 'Moved to Ready for Development on(Hidden)',
  // 'Moved to Ready for Development on 1(Hidden)',
  // 'Moved to Ready for Signoff on(Hidden)',
  // 'Moved to Ready for Signoff on 1(Hidden)',
  // 'Moved to Ready for Testing on(Hidden)',
  // 'Moved to Ready for Testing on 1(Hidden)',
  // 'Moved to To do on(Hidden)',
  'Owner',
  'Pair',
  'Pull Request',
  'Related Story',
  'Release',
  'Status',
  'Story Points',
  'Test in a QA Managed Package',
  'Created by',
  'Modified by Tags',
  'Incomplete checklist items',
  'Complete checklist items',
  'Attachments Has charts',
  'Charts and macros Data exceeding 32767 character limit'
]
